### ISSUE TITLE
Adding apps to a folder occasionally adds empty spaces and wrong app icon sizes in app drawer

### ISSUE THREAD

**Issue by ClockGen** [SimpleMobileTools/Simple-Launcher#130] opened 2023-09-21 07:03 UTC
## Description
When dragging apps from the app drawer to a folder sometimes it will add an empty space to the folder and shift the last app outside of folder bounds.  

In addition to that, apps that are dragged from app drawer temporarily have their icons shrunk down.  

## Screenshots
![Screenshot_20230921-095507_Launcher_1](https://github.com/SimpleMobileTools/Simple-Launcher/assets/12116711/0cc1c658-4edb-4ae4-91bc-d5ac3c400ad1)
![Screenshot_20230921-095849_Launcher_1](https://github.com/SimpleMobileTools/Simple-Launcher/assets/12116711/8edfe098-25ca-42ab-ad83-cca5e9879f9c)

## Steps to reproduce
Drag apps from the app drawer to a folder

## App version
5.1.0

## OS info
LineageOS 20 (Android 13)

**Comment by esensar** [comment] 2023-09-21 12:37
@ClockGen I have prepared a fix for this. Could you try it out on a custom build like the other issues?

[launcher-core-release.apk.zip](https://github.com/SimpleMobileTools/Simple-Launcher/files/12684550/launcher-core-release.apk.zip)


This one all the fixes from #140 included.

**Comment by ClockGen** [comment] 2023-09-21 13:21
@esensar I tested the apk. The bug with folders is fixed, folders don't get any empty spaces anymore.

However, bug with resized icons is still present, but it's different now: when adding icons to a folder, they stay displayed as they should, however if I'm dragging an icon just to the home screen (not into a folder), they become empty in the app drawer.

![Screenshot_20230921-161629_Launcher_1](https://github.com/SimpleMobileTools/Simple-Launcher/assets/12116711/554b91a9-1eab-4497-b570-363825aba5e6)

Here I simply dragged Acode, AIMSICD, Arcticons Dark and Bluetooth Terminal to my home screen.

The bug with scrollable widgets is still present, and this build introduced another bug: the first touch on either widget or anything inside app drawer is ignored, I can't short tap or long tap anything in the app drawer after opening it, I need to scroll it a bit first.

I can record a video, however I'm not sure how to attach it.

**Comment by esensar** [comment] 2023-09-21 13:23
I think I will be able to reproduce it.
Thank you for checking it out!
 I will take a look

**Comment by esensar** [comment] 2023-09-21 14:04
I am actually not able to reproduce the issues below. If you could provide a video, that would be helpful. You should be able to just drag and drop it into the comment box.

**Comment by ClockGen** [comment] 2023-09-21 14:16
It seems the original video was too big so I had to compress it 

https://github.com/SimpleMobileTools/Simple-Launcher/assets/12116711/9c611a9b-44aa-441c-8019-9ea721b9c0e3

**Closed** 2023-09-22 07:22 UTC
Labels: bug

**Comment by esensar** [comment] 2023-09-22 07:27
> It seems the original video was too big so I had to compress it
> test.mp4

Thank you for the video, I think I understand the issue now.
