### ISSUE TITLE
Can't move right to left in homescreen

### ISSUE THREAD

**Issue by Justauser0** [SimpleMobileTools/Simple-Launcher#71] opened 2023-06-24 09:50 UTC
Like this 

https://github.com/SimpleMobileTools/Simple-Launcher/assets/135147872/59a9c485-8c11-46f9-a906-0864c5e60ec3

**Comment by tibbi** [comment] 2023-06-25 09:46
duplicate of #47

**Closed by tibbi** 2023-06-25 09:46 UTC
