### ISSUE TITLE
Please make like this instead of scrolling bottom to top

### ISSUE THREAD

**Issue by Gamer750** [SimpleMobileTools/Simple-Launcher#146] opened 2023-09-22 17:29 UTC
![image](https://github.com/SimpleMobileTools/Simple-Launcher/assets/141329708/cf001e63-1432-4004-9a1d-d3c87169d6fe)

**Comment by tibbi** [comment] 2023-09-23 16:03
you mean horizontal scrolling?

**Comment by Gamer750** [comment] 2023-09-25 11:26
> you mean horizontal scrolling?

Yes

**Comment by tibbi** [comment] 2023-09-25 11:42
actually duplicate of #21

**Closed by tibbi** 2023-09-25 11:42 UTC
Labels: feature request
