### ISSUE TITLE
App drawer does not close after app launch

### ISSUE THREAD

**Issue by davidbtc2009** [SimpleMobileTools/Simple-Launcher#17] opened 2022-10-10 19:32 UTC
If you open the app drawer and launch an app the drawer does not close when swiping to the homescreen

**Comment by smmalmansoori** [comment] 2022-11-07 02:03
This should be a bug rather than a feature request.

Steps to reproduce:

1. Open the drawer
2. Launch an app
3. Press home button
4. Goes to the drawer

Expected behavior:

- Pressing the home button should show the home screen rather than the drawer

**Comment by Cwpute** [comment] 2022-11-12 13:49
I thought this was by design and came here to ask if it could be changed or made into an option.

This may not seem like much but it's quite irritating to have a tidy desktop ready for use, only to always be met with your open drawer when closing apps.

**Comment by HoWilgh** [comment] 2022-11-18 06:00
+1

**Comment by Cwpute** [comment] 2023-06-01 15:18
I've been wanting to use the home screen more often with a schedule widgets and shortcuts but this launcher unfortunately prevents me from accessing them by default and easily. Seeing there hasn't been an update on this issue, i think i'm going to switch to another launcher.

**Closed** 2023-07-27 14:56 UTC
Labels: feature request
