### ISSUE TITLE
Can't make apps folder in home screen

### ISSUE THREAD

**Issue by Justauser0** [SimpleMobileTools/Simple-Launcher#70] opened 2023-06-24 09:47 UTC
Can't make apps folder in home screen.
Is there any option to stop vibration in app

**Comment by tibbi** [comment] 2023-06-25 09:46
why not?

**Comment by tibbi** [comment] 2023-07-09 18:02
duplicate of #33

**Closed by tibbi** 2023-07-09 18:02 UTC

**Comment by anaxonda** [comment] 2023-07-17 08:05
I have this problem now. Cannot make folders in home screen. Using version 5.0.6 from f-droid.
